### PR TITLE
updating the lcm version to 1.2.0

### PR DESCRIPTION
**Pull request by blandry**

### CODE REVIEW

**Comment by andybarry** [comment]
This does have an issue caused by the additional jar file that used to be needed in lcm-spy, but Albert since removed.  The pkg-config file still specifies (incorrectly) that it is required.  Pull request #10 for lcm resolves that: https://github.com/lcm-proj/lcm/pull/10

When a new release comes out that includes that fix, Drake should be able to handle everything correctly with no further changes beyond bumping the version number here.

**Comment by RussTedrake** [comment]
ok.  will wait for that.

**Comment by andybarry** [comment]
This is now updated to lcm v1.2.1 and should work correctly.  Good to go.

**Comment by RussTedrake** [comment]
tried updating drake-distro master, but got this on the build server

```
*** BUILD FAILED with compilation errors. ***

Site: drake006
Build Name: master-RobotLocomotion-master
Build Server Directory: /tmp/drake-master-1306
CDash: http://kobol.csail.mit.edu/cd/index.php?project=Drake&date=20150127

Most recent commits to drake included in this build:
```
3c700ff updating lcm pod
edf8ddc update iris
a2015e9 bringing submodules up to date
39089d6 forgot to add yalmip to the build list
4bb126c add yalmip wrapper pod
```

```
...... .......... .......... 89% 47.8M 0s
10950K .......... .......... .......... .......... .......... 89% 56.5M 0s
11000K .......... .......... .......... .......... .......... 90% 65.0M 0s
11050K .......... .......... .......... .......... .......... 90%  700K 0s
11100K .......... .......... .......... .......... .......... 90% 51.9M 0s
11150K .......... .......... .......... .......... .......... 91% 54.1M 0s
11200K .......... .......... .......... .......... .......... 91% 46.0M 0s
11250K .......... .......... .......... .......... .......... 92% 80.7M 0s
11300K .......... .......... .......... .......... .......... 92%  698K 0s
11350K .......... .......... .......... .......... .......... 93% 46.8M 0s
11400K .......... .......... .......... .......... .......... 93% 45.7M 0s
11450K .......... .......... .......... .......... .......... 93% 63.3M 0s
11500K .......... .......... .......... .......... .......... 94% 71.4M 0s
11550K .......... .......... .......... .......... .......... 94%  700K 0s
11600K .......... .......... .......... .......... .......... 95% 45.5M 0s
11650K .......... .......... .......... .......... .......... 95% 43.0M 0s
11700K .......... .......... .......... .......... .......... 95% 68.1M 0s
11750K .......... .......... .......... .......... .......... 96% 73.1M 0s
11800K .......... .......... .......... .......... .......... 96% 60.8M 0s
11850K .......... .......... .......... .......... .......... 97%  695K 0s
11900K .......... .......... .......... .......... .......... 97% 53.6M 0s
11950K .......... .......... .......... .......... .......... 97% 47.9M 0s
12000K .......... .......... .......... .......... .......... 98% 63.0M 0s
12050K .......... .......... .......... .......... .......... 98% 73.3M 0s
12100K .......... .......... .......... .......... .......... 99%  699K 0s
12150K .......... .......... .......... .......... .......... 99% 40.6M 0s
12200K .......... .......... .......... .......... .......... 99% 69.5M 0s
12250K ......                                                100%
65.4M=4.5s

2015-01-27 10:49:30 (2.66 MB/s) - `lcm-1.2.1.zip' saved [12550954/12550954]

lcm_logger.c: In function ‘write_thread’:
lcm_logger.c:260:13: warning: implicit declaration of function ‘fdatasync’
[-Wimplicit-function-declaration]
java.io.IOException: META-INF : could not create directory
	at sun.tools.jar.Main.extractFile(Main.java:932)
	at sun.tools.jar.Main.extract(Main.java:870)
	at sun.tools.jar.Main.run(Main.java:260)
	at sun.tools.jar.Main.main(Main.java:1167)
make[3]: *** [build/com/jidesoft/comparator/AlphanumComparator.class] Error
1
make[3]: *** Waiting for unfinished jobs....
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
make[2]: *** [install-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by andybarry** [comment]
It looks like it might be a permissions issue -- the error is "could not create directory"

Perhaps similar to this: http://stackoverflow.com/questions/18052460/error-while-trying-to-extract-jar-file

What do the permissons on the server look like for that user?

**Pull request merged**
