### PR TITLE
De-subtree

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Move LCM sources to the repository root, eliminating the extra directory structure. This makes it possible to build directly with CMake (in particular, it makes it possible for consumers to treat the repository as a bog standard "CMake POD").

See also related discussion in RobotLocomotion/drake#1843.

Note: I haven't tested the update script, as it requires a newer version of git than I have.

### CODE REVIEW

**Comment by RussTedrake** [comment]
the expectation is that the update script will still work... correct?

**Comment by mwoehlke-kitware** [comment]
> the expectation is that the update script will still work... correct?

I made my best guess at modifying it to work without a subtree... The folks that are more familiar with it are unfortunately out today; I'll probably ask one of them to test Monday.

**Comment by mwoehlke-kitware** [comment]
@RussTedrake, I talked to folks around here and our consensus seems to be that it would make more sense for the POD-ified LCM repo to just be a fork of upstream with changes applied. (Then you just use 'git merge' to do updates.)

Here's my new plan: I will import the upstream repo as a separate tree, drop the update script, then merge the two together so that future updates can be done easily. Once this is ready to go, I'll push it as an update to this PR.

Relevant question: do we want the repo to appear as a github fork of upstream?

**Comment by patmarion** [comment]
My 2 cents-

Fork upstream to a new RobotLocomotion repo and add commits that introduce the CMakeified build. Don't bother to merge the lcm-pod history.  The lcm-pod repo can be retired.  Hopefully the new commits could be contributed upstream.  (I would suggest a standard cmake build and not a pod-style build :-)

**Comment by mwoehlke-kitware** [comment]
@patmarion, that would be my preference also, but I was under the impression that "follow PODS" was still a requirement? Is that no longer the case?

If not, can someone please fork (or approve for me to do so) upstream to a new RobotLocomotion repo "lcm"?

> Hopefully the new commits could be contributed upstream. (I would suggest a standard cmake build and not a pod-style build :-)

I suspect upstream is more likely to accept a "regular" CMake build system than a PODS variation :smile:.

**Comment by RussTedrake** [comment]
That sounds good. Thank you. It’s the same thing we’ve just done with bullet.
I will fork lcm to RobotLocomotion/lcm and give you permissions to get you
started.
- Russ

**Comment by mwoehlke-kitware** [comment]
Abandoned... may want to merge #16 in the mean time, but the new long term plan is to properly CMake-ify lcm itself and go from there.

**Pull request closed without merging**
