### PR TITLE
Update cmake branch to use lcm 1.3.0

### PR DESCRIPTION
**Pull request by jhoare**
This pull request moves the location of the included lcm from ``lcm-1.0.0`` to ``lcm/lcm-src``. 

Additionally, this request includes the ``update-comon.sh`` and ``update.sh`` scripts which are from the VTK project and is used to conveniently track the changes of upstream projects. 

The ``update-common.sh`` script tracks the upstream project in an ``upstream-$projname`` (.e.g ``upstream-lcm`` branch and then uses a subtree merge to update the main branch (in our case the ``cmake`` branch for now.) 

To update the version of LCM in the future, change the version/tag in the ``update.sh`` script to the desired version/tag and run the script. 

In addition to this pull request, the upstream-lcm branch from my fork should also be pushed into this repository. It doesn't look like github will allow me to create a pull request to do that.

### CODE REVIEW

**Comment by RussTedrake** [comment]
It looks like you are zapping all of the cmake logic that we put into the cmake branch and relacing it with the upstream lcm?

I think the plan was to update master to point to updated upstream lcm, then merge it into this branch.  Having a local coly of the source feels inevitable for now, until we push to upstream lcm.

**Comment by jhoare** [comment]
No all the CMake logic that you put in for version 1.0.0 is still there, although I needed to update a number of CMakeList.txt files to build the latest version. Build tests are failing still for some reason regarding lcm-java. 

Regarding the plan drake checks out the ``cmake`` branch, I thought we were leaving master alone for now, and updating the ``cmake`` branch to have the latest lcm. 

After we get that done, the next step could be to attempt to upstream the cmake work into lcm, and once that is done we can update to downloading and using upstream lcm.

**Comment by RussTedrake** [comment]
ok, excellent.  the github diff was unable to show me that those files moved (instead of getting deleted) because the diff was too big.  But I see it now, stepping through the individual commits.  
Will wait for the java fix.  Let me know when you think it's ready.  And thanks!

**Comment by RussTedrake** [comment]
And yes - you were correct to do this in the cmake branch.  I would only have used master if you wanted to update to lcm in the non-cmake version (e.g. if updating the cmake branch was too hard).  but you made far more progress than I realized!

**Comment by jhoare** [comment]
@RussTedrake Looks like this is building correctly now and all tests are passing in RobotLocomotion/drake#1698 . 

Do many of the tests that run use lcm? If not maybe someone more familiar with running the whole system should try out that branch first to see if any weird issues come up.

**Pull request merged**
